version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=1234qwer
      - MYSQL_DATABASE=movie_land_cinema_system_db
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=user1234
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  app:
    container_name: app
    image: movie-land-cinema-system
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    restart: always

volumes:
  mysql-db: